import type { Scenario } from "./types.ts";
import { at } from "./types.ts";
import { EARLY_BIRD, NIGHT_OWL, TWIN_PEAKS } from "./energy.ts";

/**
 * 固定测试场景库（计划文档 §9 周二交付物）。
 * 每个场景的 note 附"人类合理排法"对照，作为求解器行为的直觉锚点。
 * 时间用 at(day, hour) 表达；1h = 4 槽。
 */

export const SCENARIOS: Scenario[] = [
  {
    name: "01-light-day",
    note: "轻载日。人类排法：上午高能写报告（避开 10-11 会议），杂务下午，邮件随便塞低能时段。",
    curve: EARLY_BIRD,
    meetings: [{ id: "m1", title: "周会", start: at(0, 10), end: at(0, 11) }],
    tasks: [
      {
        id: "report",
        title: "写季度报告",
        duration: 8,
        splittable: true,
        minBlock: 4,
        load: 3,
        priority: 3,
        deadline: at(1, 0),
      },
      {
        id: "email",
        title: "清邮箱",
        duration: 2,
        splittable: true,
        minBlock: 2,
        load: 1,
        priority: 1,
      },
      {
        id: "errand",
        title: "取快递+杂务",
        duration: 4,
        splittable: false,
        minBlock: 4,
        load: 2,
        priority: 2,
      },
    ],
  },
  {
    name: "02-meeting-heavy",
    note: "会议密集日（5 个会占满白天）。人类排法：深度任务整个推到第 1 天的高能区，碎缝只塞轻活。",
    curve: TWIN_PEAKS,
    meetings: [
      { id: "m1", title: "站会", start: at(0, 9), end: at(0, 10) },
      { id: "m2", title: "评审", start: at(0, 10.5), end: at(0, 12) },
      { id: "m3", title: "1on1", start: at(0, 13), end: at(0, 14) },
      { id: "m4", title: "客户会", start: at(0, 15), end: at(0, 16.5) },
      { id: "m5", title: "同步会", start: at(0, 17), end: at(0, 18) },
    ],
    tasks: [
      {
        id: "design",
        title: "架构设计稿",
        duration: 6,
        splittable: false,
        minBlock: 6,
        load: 3,
        priority: 3,
        deadline: at(1, 23),
        hardDeadline: true,
      },
      {
        id: "slack",
        title: "回消息",
        duration: 2,
        splittable: true,
        minBlock: 2,
        load: 1,
        priority: 2,
      },
      {
        id: "notes",
        title: "整理会议纪要",
        duration: 3,
        splittable: true,
        minBlock: 2,
        load: 1,
        priority: 1,
      },
    ],
  },
  {
    name: "03-deadline-clash",
    note: "双硬截止冲突：两个深度任务都要在第 0 天 13:00 前交。人类排法：背靠背塞进上午高能区，中间留口气。",
    curve: EARLY_BIRD,
    meetings: [],
    tasks: [
      {
        id: "pitch",
        title: "投资人 deck",
        duration: 6,
        splittable: false,
        minBlock: 6,
        load: 3,
        priority: 3,
        deadline: at(0, 13),
        hardDeadline: true,
      },
      {
        id: "patch",
        title: "紧急修复 + 验证",
        duration: 6,
        splittable: false,
        minBlock: 6,
        load: 3,
        priority: 3,
        deadline: at(0, 13),
        hardDeadline: true,
      },
    ],
  },
  {
    name: "04-deep-night-owl",
    note: "夜猫曲线 × 深度任务。人类排法：深活全排 18 点以后的高能区，白天别硬写。",
    curve: NIGHT_OWL,
    meetings: [],
    tasks: [
      {
        id: "paper",
        title: "论文章节",
        duration: 8,
        splittable: true,
        minBlock: 4,
        load: 3,
        priority: 3,
        deadline: at(3, 0),
      },
      {
        id: "code",
        title: "核心模块重构",
        duration: 8,
        splittable: true,
        minBlock: 4,
        load: 3,
        priority: 2,
        deadline: at(4, 0),
      },
      {
        id: "chores",
        title: "报销+行政",
        duration: 4,
        splittable: true,
        minBlock: 2,
        load: 1,
        priority: 1,
      },
    ],
  },
  {
    name: "05-unsplittable-long",
    note: "3 小时不可拆深度任务（如录课/长实验）。第 0 天高能区被会议切碎放不下 → 应整块排到第 1 天上午。",
    curve: EARLY_BIRD,
    meetings: [{ id: "m1", title: "晨会", start: at(0, 9), end: at(0, 10) }],
    tasks: [
      {
        id: "recording",
        title: "录制课程（不可中断）",
        duration: 12,
        splittable: false,
        minBlock: 12,
        load: 3,
        priority: 3,
        deadline: at(2, 0),
      },
      {
        id: "prep",
        title: "课件检查",
        duration: 2,
        splittable: true,
        minBlock: 2,
        load: 2,
        priority: 2,
      },
    ],
  },
  {
    name: "06-all-splittable-fragments",
    note: "全可拆任务 × 碎片化日程。人类排法：见缝插针，但每段不小于最小块长。",
    curve: TWIN_PEAKS,
    meetings: [
      { id: "m1", title: "会A", start: at(0, 9), end: at(0, 10) },
      { id: "m2", title: "会B", start: at(0, 11), end: at(0, 12) },
      { id: "m3", title: "会C", start: at(0, 14), end: at(0, 15.5) },
      { id: "m4", title: "会D", start: at(0, 17), end: at(0, 18) },
    ],
    tasks: [
      {
        id: "review",
        title: "代码评审",
        duration: 6,
        splittable: true,
        minBlock: 2,
        load: 2,
        priority: 3,
        deadline: at(1, 0),
      },
      {
        id: "docs",
        title: "补文档",
        duration: 8,
        splittable: true,
        minBlock: 4,
        load: 2,
        priority: 2,
      },
      {
        id: "inbox",
        title: "邮件+消息",
        duration: 4,
        splittable: true,
        minBlock: 2,
        load: 1,
        priority: 1,
      },
    ],
  },
  {
    name: "07-overload-infeasible",
    note: "超载不可行日：5 个 3 小时不可拆任务全要第 0 天交，物理上放不下。期望：优雅丢弃并报告，而非崩溃或排出违约解。",
    curve: EARLY_BIRD,
    meetings: [],
    tasks: [1, 2, 3, 4, 5].map((i) => ({
      id: `job${i}`,
      title: `任务 ${i}`,
      duration: 12,
      splittable: false,
      minBlock: 12,
      load: 2 as const,
      priority: (i <= 2 ? 3 : i === 3 ? 2 : 1) as 1 | 2 | 3,
      deadline: at(1, 0),
      hardDeadline: true,
    })),
  },
  {
    name: "08-week-rolling",
    note: "7 天滚动：每个工作日有晨会，任务截止分散在第 2~6 天。人类排法：深活靠各天高能区，截止近的先做。",
    curve: TWIN_PEAKS,
    meetings: [0, 1, 2, 3, 4].map((d) => ({
      id: `standup-${d}`,
      title: "晨会",
      start: at(d, 9),
      end: at(d, 9.5),
    })),
    tasks: [
      {
        id: "spec",
        title: "需求规格",
        duration: 8,
        splittable: true,
        minBlock: 4,
        load: 3,
        priority: 3,
        deadline: at(2, 0),
      },
      {
        id: "impl",
        title: "功能实现",
        duration: 12,
        splittable: true,
        minBlock: 4,
        load: 3,
        priority: 3,
        deadline: at(5, 0),
      },
      {
        id: "test",
        title: "测试用例",
        duration: 6,
        splittable: true,
        minBlock: 2,
        load: 2,
        priority: 2,
        deadline: at(6, 0),
      },
      {
        id: "blog",
        title: "技术博客",
        duration: 6,
        splittable: true,
        minBlock: 4,
        load: 2,
        priority: 1,
      },
      {
        id: "admin",
        title: "周报+行政",
        duration: 3,
        splittable: true,
        minBlock: 2,
        load: 1,
        priority: 1,
        deadline: at(4, 23),
      },
      {
        id: "interview",
        title: "面试准备",
        duration: 4,
        splittable: false,
        minBlock: 4,
        load: 2,
        priority: 2,
        deadline: at(3, 0),
      },
    ],
  },
];

export function getScenario(name: string): Scenario {
  const s = SCENARIOS.find((x) => x.name === name);
  if (!s) throw new Error(`未知场景: ${name}`);
  return s;
}
